{
 "title": "BuildGrid Bots",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "AggregateMethod",
    "label": "Aggregate Method",
    "query": "lower, mean, mean_90, median, upper, upper_90"
   }
  ]
 },
 "panels": [
  {
   "title": "CreateBotSession average duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.buildgrid.bots.create-bot-session-time.$AggregateMethod"
    },
    {
     "target": "stats.timers.buildgrid.instance.bots.create-bot-session-time.$AggregateMethod"
    }
   ]
  },
  {
   "title": "UpdateBotSession average duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "stats.timers.buildgrid.bots.update-bot-session-time.$AggregateMethod"
    },
    {
     "target": "stats.timers.buildgrid.instance.bots.update-bot-session-time.$AggregateMethod"
    }
   ]
  },
  {
   "title": "High lease assignment/no work timings",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "stats.timers.buildgrid.instance.bots.assign-job-leases-time.$AggregateMethod"
    }
   ]
  },
  {
   "title": "Bot Count by Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.buildgrid.bots-count.*)"
    }
   ]
  }
 ]
}