{
 "title": "BuildGrid CAS",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "AggregateMethod",
    "label": "Aggregate Method",
    "query": "lower, mean, mean_90, median, upper, upper_90"
   }
  ]
 },
 "panels": [
  {
   "title": "CAS/ByteStream request counts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(stats.timers.buildgrid.batch-read-blobs.count, 'BatchReadBlobs')"
    },
    {
     "target": "alias(stats.timers.buildgrid.batch-update-blobs.count, 'BatchUpdateBlobs')"
    },
    {
     "target": "alias(stats.timers.buildgrid.bytestream-read.count, 'ByteStream Read')"
    },
    {
     "target": "alias(stats.timers.buildgrid.bytestream-write.count, 'ByteStream Write')"
    }
   ]
  },
  {
   "title": "CAS bytes downloaded/uploaded count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "stats.buildgrid.instance.cas-downloaded-bytes"
    },
    {
     "target": "stats.buildgrid.instance.cas-uploaded-bytes"
    }
   ]
  },
  {
   "title": "ByteStream Read Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read request durations",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "stats.timers.buildgrid.batch-read-blobs.$AggregateMethod"
      },
      {
       "target": "stats.timers.buildgrid.bytestream-read.$AggregateMethod"
      },
      {
       "target": "stats.timers.buildgrid.instance.bytestream-read.$AggregateMethod"
      },
      {
       "target": "stats.timers.buildgrid.instance.batch-read-blobs.$AggregateMethod"
      }
     ]
    },
    {
     "title": "CAS ByteStream Read LRU Cache Hits/Misses",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "alias(stats.timers.buildgrid.cas-withcache-get-blob-hits.sum, 'Cache Hits')"
      },
      {
       "target": "alias(stats.timers.buildgrid.cas-withcache-get-blob-misses.sum, 'Cache Misses')"
      }
     ]
    }
   ]
  },
  {
   "title": "BatchReadBlobs Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "BatchReadBlobs duration",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "stats.timers.buildgrid.instance.batch-read-blobs.$AggregateMethod"
      }
     ]
    },
    {
     "title": "CAS BatchReadBlobs LRU Cache Hits/Misses",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "alias(stats.timers.buildgrid.cas-withcache-bulk-read-hits.sum, 'Cache Hits')"
      },
      {
       "target": "alias(stats.timers.buildgrid.cas-withcache-bulk-read-misses.sum, 'Cache Misses')"
      }
     ]
    }
   ]
  },
  { "title": "ByteStream Write Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Write request durations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "stats.timers.buildgrid.bytestream-write.$AggregateMethod"
    }
   ]
  }
 ]
}