{
 "title": "BuildGrid Cleanup",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Cleanup runtime",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "alias(scale(stats.timers.buildgrid.instance.cleanup.runtime-timer.mean, 0.001), 'Cleanup Runtime (seconds)')"
    }
   ]
  },
  {
   "title": "Mark as deleted duration",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "target": "stats.timers.buildgrid.instance.cleanup.index.mark-as-deleted-timer.mean"
    }
   ]
  },
  {
   "title": "S3 Bulk Delete duration",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "target": "stats.timers.buildgrid.instance.cleanup.storage.bulk-delete-timer.mean"
    }
   ]
  },
  {
   "title": "Index Bulk Delete duration",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "target": "stats.timers.buildgrid.instance.cleanup.index.bulk-delete-timer.mean"
    }
   ]
  }
 ]
}