{
 "title": "BuildGrid CAS Index",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "AggregateMethod",
    "label": "Aggregate Method",
    "query": "lower, mean, mean_90, median, upper, upper_90"
   }
  ]
 },
 "panels": [
  {
   "title": "`get_blob` durations",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(stats.timers.buildgrid.instance.cas.index.get-blob-time.$AggregateMethod, 'Overall `get_blob` duration')"
    },
    {
     "target": "alias(stats.timers.buildgrid.instance.cas.index.blob-timestamp-update-time.$AggregateMethod, 'Timestamp update duration')"
    }
   ]
  },
  {
   "title": "Average time to save digests in index",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "stats.timers.buildgrid.instance.cas.index.save-digests-time.$AggregateMethod"
    }
   ]
  },
  {
   "title": "Bulk select digest duration",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "stats.timers.buildgrid.instance.cas.index.bulk-select-digest-time.$AggregateMethod"
    }
   ]
  },
  {
   "title": "Bulk timestamp update duration",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "stats.timers.buildgrid.instance.cas.index.bulk-timestamp-update-time.$AggregateMethod"
    }
   ]
  }
 ]
}