{
 "title": "BuildGrid Scheduler Backend",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "AggregateMethod",
    "label": "Aggregate Method",
    "query": "lower, mean, mean_90, median, upper, upper_90"
   }
  ]
 },
 "panels": [
  {
   "title": "Time taken to insert rows",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(stats.timers.buildgrid.instance.datastore.all.create-job-time.$AggregateMethod, 'Jobs')"
    },
    {
     "target": "alias(stats.timers.buildgrid.instance.datastore.all.create-operation-time.$AggregateMethod, 'Operations')"
    },
    {
     "target": "alias(stats.timers.buildgrid.instance.datastore.all.create-lease-time.$AggregateMethod, 'Leases')"
    }
   ]
  },
  {
   "title": "Time taken to update rows",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(stats.timers.buildgrid.instance.datastore.all.update-job-time.$AggregateMethod, 'Jobs')"
    },
    {
     "target": "alias(stats.timers.buildgrid.instance.datastore.all.update-lease-time.$AggregateMethod, 'Leases')"
    }
   ]
  },
  {
   "title": "Time to get a Job",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(stats.timers.buildgrid.instance.datastore.all.get-job-by-digest-time.$AggregateMethod, 'By Action Digest')"
    },
    {
     "target": "alias(stats.timers.buildgrid.instance.datastore.all.get-job-by-name-time.$AggregateMethod, 'By Job Name')"
    },
    {
     "target": "alias(stats.timers.buildgrid.instance.datastore.all.get-job-by-operation-time.$AggregateMethod, 'By Operation Name')"
    }
   ]
  },
  {
   "title": "Time to store ExecuteResponse messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "stats.timers.buildgrid.instance.datastore.sql.store-response-time.$AggregateMethod"
    }
   ]
  },
  {
   "title": "Time to handle Job update notifications",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "stats.timers.buildgrid.instance.datastore.all.check-for-update-time.$AggregateMethod"
    }
   ]
  },
  {
   "title": "Time to run a ListOperations filter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "stats.timers.buildgrid.instance.datastore.all.list-operations-time.$AggregateMethod"
    }
   ]
  }
 ]
}