apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildbox-run-bubblewrap
spec:
  replicas: 3
  selector:
    matchLabels:
      app: buildbox-run-bubblewrap
  template:
    metadata:
      labels:
        app: buildbox-run-bubblewrap
    spec:
      containers:
        - name: buildbox-run-bubblewrap
          image: registry.gitlab.com/buildgrid/buildgrid.hub.docker.com/buildbox:nightly
          env:
            - name: BUILDGRID_SERVER_URL
              value: http://bgd-execution:50051
            - name: CAS_SERVER_URL
              value: http://bgd-cas:50052
            - name: RUNNER_BINARY
              value: buildbox-run-bubblewrap
            - name: INSTANCE_NAME
              value: buildgrid
            - name: PLATFORM_PROPERTY_OPTS
              value: "--platform runner=bubblewrap --platform OSFamily=linux --platform ISA=x86-64"
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
