apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  labels:
    app: nginx
data:
  nginx.conf: |
    worker_processes auto;
    error_log stderr debug;

    events {
      worker_connections 1024;
    }

    http {
      access_log /dev/stdout;
      client_max_body_size 0;
      proxy_request_buffering off;
      server {
        listen 50051 http2;
        server_name localhost;
        keepalive_timeout 7200s;
        keepalive_requests 100000;

        grpc_read_timeout 7200s;
        grpc_send_timeout 7200s;

        # Capabilities is currently handled by the Execution service,
        # see https://gitlab.com/BuildGrid/buildgrid/-/issues/174
        location /build.bazel.remote.execution.v2.Capabilities {
          grpc_pass grpc://bgd-execution:50051;
        }

        location /build.bazel.remote.execution.v2.Execution {
          grpc_pass grpc://bgd-execution:50051;
        }

        location /google.longrunning.Operations {
          grpc_pass grpc://bgd-execution:50051;
        }

        location /build.bazel.remote.execution.v2.ContentAddressableStorage {
          grpc_pass grpc://bgd-cas:50052;
        }

        location /google.bytestream.ByteStream {
          grpc_pass grpc://bgd-cas:50052;
        }

        location /build.bazel.remote.execution.v2.ActionCache {
          grpc_pass grpc://bgd-cache:50053;
        }
      }
    }