apiVersion: v1
kind: Service
metadata:
  name: bgd-execution
  labels:
    app: bgd-execution
spec:
  ports:
    - port: 50051
      protocol: TCP
  selector:
    app: bgd-execution
---
apiVersion: v1
kind: Service
metadata:
  name: bgd-cas
  labels:
    app: bgd-cas
spec:
  ports:
    - port: 50052
      protocol: TCP
  selector:
    app: bgd-cas
---
apiVersion: v1
kind: Service
metadata:
  name: bgd-cache
  labels:
    app: bgd-cache
spec:
  ports:
    - port: 50053
      protocol: TCP
  selector:
    app: bgd-cache
