{
 "title": "BuildGrid Cleanup",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Cleanup runtime",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "alias(scale(stats.timers.buildgrid.instance.cleanup.runtime-timer.mean, 0.001), 'Cleanup Runtime (seconds)')"
    }
   ]
  },
  {
   "title": "Mark as deleted duration",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "target": "stats.timers.buildgrid.instance.cleanup.index.mark-as-deleted-timer.mean"
    }
   ]
  },
  {
   "title": "S3 Bulk Delete duration",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "target": "stats.timers.buildgrid.instance.cleanup.storage.bulk-delete-timer.mean"
    }
   ]
  },
  {
   "title": "Index Bulk Delete duration",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "target": "stats.timers.buildgrid.instance.cleanup.index.bulk-delete-timer.mean"
    }
   ]
  }
 ]
}
{
 "title": "BuildGrid Scheduler",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Incomplete Job Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(exclude(stats.gauges.buildgrid.instance.job-count.*, 'COMPLETED'))"
    }
   ]
  },
  {
   "title": "Operation Count by Stage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "exclude(aliasByMetric(stats.gauges.buildgrid.instance.operation-count.*), 'COMPLETED')"
    }
   ]
  },
  {
   "title": "Lease Count by State",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "exclude(aliasByMetric(stats.gauges.buildgrid.instance.lease-count.*), 'COMPLETED')"
    }
   ]
  },
  {
   "title": "Queued Jobs",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 1, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "stats.gauges.buildgrid.instance.job-count.QUEUED"
    }
   ]
  },
  {
   "title": "Completed Jobs",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "stats.gauges.buildgrid.instance.job-count.COMPLETED"
    }
   ]
  },
  {
   "title": "Bot Count by Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.buildgrid.bots-count.*)"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.buildgrid.instance.clients-count, 'Number of clients')"
    }
   ]
  }
 ]
}